### ISSUE TITLE
inconsistent doc for Registry

### ISSUE THREAD

**Issue by alekc** [globallogicuki/provider-harbor#25]
Given this config
```yaml
apiVersion: registry.harbor.crossplane.io/v1alpha1
kind: Registry
metadata:
  name: dockerhub
spec:
#  providerConfigRef:
#    name: ${provider_name}
  forProvider:
    providerName: ${provider_name}
    name: docker.io
    accessId: xx
    accessSecretSecretRef:
      key: "docker.io"
      name: docker-registries
      namespace: harbor
```
It was giving following error 
```
one or more objects failed to apply, reason: Registry.registry.harbor.crossplane.io "dockerhub" is invalid: spec: Invalid value: "object": spec.forProvider.endpointUrl is a required parameter (retried 5 times).
```

Its not marked as required on doc 

![Image](https://github.com/user-attachments/assets/b225ade7-3d3b-49ec-933d-dad2f4539852)
