### ISSUE TITLE
Updating retention policy leads to 405 error

### ISSUE THREAD

**Issue by raweber42** [globallogicuki/provider-harbor#28]
Hi! First of all: Thanks for putting in the work to create this provider!

I have the following issue: I created a couple of retention-policies. Then I realized my excluded tags were incorrect. So I changed the tags. But now this update results in the following error:

```
Message:               apply failed: [ERROR] unexpected status code got: 405 expected: 200                                                                                                                   │
│  {"errors":[{"code":"METHOD_NOT_ALLOWED","message":"method PUT is not allowed, but [POST] are"}]}
```

I didn't have time yet to check the source code, but it seems like the wrong API endpoint is being called by ?terraform?.
I am happy to contribute, if that's necessary!

Cheers

**Comment by lornest** [comment]
Hey @raweber42 

Thanks for raising. I'm out at KubeCon Europe this week, but I'll try to take a look into this at some point.

If you do happen to figure out where the issue lies, feel free to contribute or let me know and I can pick up 🙂

**Comment by raweber42** [comment]
Alright, I got it working now 😅 Was a configuration issue on my side:

Firstly, I had an invalid CRON schedule (`0 2 * * WED *` is _not_ supported). But somehow I could only see this error in the alphabetically first of all the rules. For the others I had the `405` error.

Furthermore, I realized that I misunderstood how the rules work.

My - incorrect - config was:
```
rule:
      - nDaysSinceLastPull: 5
        nDaysSinceLastPush: 10
        tagMatching: "**"
```

-> Problem here is, that only one of both can be specified _per rule_. I was not aware of that (you could guess though by checking the UI of harbor). Maybe we could add documentation saying that only one of this properties can be defined _per rule_. By the way: I did _not_ get an error. The `nDaysSinceLastPush: 10` simply got ignored altogether.

The correct and working config looks like this:
```
rule:
      - nDaysSinceLastPull: 5
        repoMatching: "**"
        tagMatching: "**"
      - nDaysSinceLastPush: 10
        repoMatching: "**"
        tagMatching: "**"
```

Note: I also had to mention one of `repoMatching` or `repoExcluding`. If you don't, it f*cks up something in the background of Harbor I think. Because when navigating to the UI, you can see. That the UI is broken - you can only see one rule although it says there are two - and there is an endless loading indicator in the botton (see screenshot below)

![Image](https://github.com/user-attachments/assets/49f66cec-0885-49ff-a573-dadec8dbb1c6)
