### ISSUE TITLE
Replication filter not working properly

### ISSUE THREAD

**Issue by tschlaepfer** [globallogicuki/provider-harbor#9]
Hi @lornest, I tested the replication configuration more thoroughly and found that the filter configuration is not working properly. 

I configured the following replication: 
```
apiVersion: registry.harbor.crossplane.io/v1alpha1
kind: Replication
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: demo-replication
spec:
  forProvider:
    action: pull
    name: demo-replication
    registryIdRef:
      name: docker-registry
    destNamespace: demo
    destNamespaceReplace: 1
    schedule: "0 0 2 * * *"
    executeOnChanged: false
    filters:
      - name: 4data/demo
        tag: "*" 
        decoration: matches
  providerConfigRef:
    name: harbor-provider
  ```

However, when the object is applied the resulting configuration in Harbor looks like this, where the filter "Name" parameter is missing. 

![image](https://github.com/user-attachments/assets/589d6106-d336-47b6-836b-e0d5fb7c9761)

I have tested several different configuration but never managed to get the "Name" parameter configured properly. Could you please have a look at this issue?

**Comment by tschlaepfer** [comment]
@lornest have you been able to replicate my issue?

**Comment by asperan** [comment]
Hi, I have the same problem described by @tschlaepfer . I'm using the provider version `v0.2.0`.

My configuration of the Replication is the following:
```
apiVersion: registry.harbor.crossplane.io/v1alpha1
kind: Replication
metadata:
  name: test-replication
spec:
  forProvider:
    action: push
    description: ""
    destNamespace: ""
    destNamespaceReplace: 0 # One of -1, 0, 1, 2, 3
    executeOnChanged: false
    filters:
      - decoration: matches
        labels: []
        name: "test/**"
        resource: ""
        tag: "**"
    name: "test-replication"
    override: true
    registryIdRef:
      name: "replica-harbor"
    schedule: event_based
```

and the result is the same:
![Image](https://github.com/user-attachments/assets/6119cf09-c221-494a-b3a5-e87efdfe05fe)

By looking at the values returned by the Harbor API, I have found that the Replication created from the web UI has the following content:
```
{
    "copy_by_chunk": false,
    "creation_time": "2025-02-13T10:53:35.585Z",
    "dest_namespace_replace_count": 0,
    "dest_registry": {
      "creation_time": "2025-02-13T10:51:21.360Z",
      "credential": {},
      "id": 2,
      "insecure": true,
      "name": "replica-harbor",
      "status": "healthy",
      "type": "harbor",
      "update_time": "2025-02-13T10:51:21.360Z",
      "url": "http://replica-harbor.default.svc"
    },
    "enabled": true,
    "filters": [
      {
        "type": "name",
        "value": "library/**"
      },
      {
        "decoration": "matches",
        "type": "tag",
        "value": "**"
      }
    ],
    "id": 1,
    "name": "library-replication",
    "override": true,
    "speed": 0,
    "src_registry": {
      "creation_time": "0001-01-01T00:00:00.000Z",
      "credential": {
        "access_secret": "*****",
        "type": "secret"
      },
      "id": 0,
      "insecure": true,
      "name": "Local",
      "status": "healthy",
      "type": "harbor",
      "update_time": "0001-01-01T00:00:00.000Z",
      "url": "http://main-harbor-core:80"
    },
    "trigger": {
      "trigger_settings": {},
      "type": "event_based"
    },
    "update_time": "2025-02-13T10:53:35.585Z"
  }
```

while the Replication created by this provider has the following content:
```
{
    "copy_by_chunk": false,
    "creation_time": "2025-02-13T11:08:25.137Z",
    "dest_namespace_replace_count": 0,
    "dest_registry": {
      "creation_time": "2025-02-13T10:51:21.360Z",
      "credential": {},
      "id": 2,
      "insecure": true,
      "name": "replica-harbor",
      "status": "healthy",
      "type": "harbor",
      "update_time": "2025-02-13T10:51:21.360Z",
      "url": "http://replica-harbor.default.svc"
    },
    "enabled": true,
    "filters": [
      {
        "decoration": "matches",
        "type": "tag",
        "value": "**"
      }
    ],
    "id": 2,
    "name": "test-replication",
    "override": true,
    "speed": 0,
    "src_registry": {
      "creation_time": "0001-01-01T00:00:00.000Z",
      "credential": {
        "access_secret": "*****",
        "type": "secret"
      },
      "id": 0,
      "insecure": true,
      "name": "Local",
      "status": "healthy",
      "type": "harbor",
      "update_time": "0001-01-01T00:00:00.000Z",
      "url": "http://main-harbor-core:80"
    },
    "trigger": {
      "trigger_settings": {},
      "type": "event_based"
    },
    "update_time": "2025-02-13T11:08:25.137Z"
  }
```

The only difference (aside the name and the timestamps) is the filter part: the one created in the web UI has the additional filter:
```
{
  "type": "name",
  "value": "library/**"
}
```
which cannot be set in the Replication CR.

If needed, I'll gladly provide more informations.
